scenario_number: 0
render_mode: "matplotlib"
agent_module_path: "./BalloonPoppingGymEnv/agents/workshop_agent.py"
agent_class_name: "VerticalBaselineAgent"
agent_name: "Workshop Vertical Baseline"
agent_kwargs:
  launch_time: 1.0
  throttle: 1.0
leaderboard_submission: false
